Suggestion #56
mindustry-antigrief/mindustry-client pull request #61
Opened 2022-01-15 15:43 UTC by TomtheCoder2

implemented Suggestion #56

2022-01-22 19:22 UTC, TomtheCoder2 commented
accidentally deleted the branch lol

2022-01-23 16:14 UTC, buthed010203 requested changes

2022-01-23 16:14 UTC, buthed010203 commented on core/src/mindustry/ui/CoreItemsDisplay.java
> +    private final HashMap<Item, Float> lastItemsAveraged = new HashMap<>();
Use Arc's ObjectFloatMap instead.

2022-01-23 16:14 UTC, buthed010203 commented on core/src/mindustry/ui/CoreItemsDisplay.java
> +        // add all items to the lists, else NullPointerException
ObjectFloatMap get has a default for when its not found

2023-06-13 16:10 UTC, BalaM314 commented
Closing as I'm pretty sure this feature has been implemented

2023-06-13 16:10 UTC, closed without merging