Add some translates
mindustry-antigrief/mindustry-client pull request #66
Opened 2022-02-04 11:38 UTC by lliioollcn

2022-02-10 17:45 UTC, Weathercold requested changes

2022-02-10 17:45 UTC, Weathercold commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.processorconfigs.description =F出于某种原因，有些人不能很好地配置逻辑处理器，这使他们能够更容易地配置逻辑处理器
the F

2022-02-10 17:45 UTC, Weathercold commented on core/assets/bundles/bundle_zh_CN.properties
> +client.aliastaken = 别称
“重复别称”? or “别称已被使用”?

2022-02-10 17:45 UTC, Weathercold commented on core/assets/bundles/bundle_zh_CN.properties
> +client.unassist = 阻止玩家进入建筑
阻止玩家建造

2022-02-10 17:45 UTC, Weathercold commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.instantturn.name = 转动单位
“瞬间转动单位” would be better since it’s instantaneous

2022-02-10 17:45 UTC, Weathercold commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.blockreplace.description = 按住Shift旋转
“旋转” means rotate, maybe “切换” or “倒置”?
`setting.blockreplace.name` can be “改变自动建筑放置的行为”

2022-02-11 17:10 UTC, buthed010203 commented
Is this ready to merge?

2022-02-15 13:13 UTC, Lin-cat commented on core/assets/bundles/bundle_zh_CN.properties
> +client.rotated = 旋转
个人建议
更改了
建造了
拆除了
被摧毁
拾取了
放下了
旋转了

2022-02-15 13:17 UTC, Lin-cat commented on core/assets/bundles/bundle_zh_CN.properties
> +client.plans = 计划: {0}
plans在官中里叫规划

2022-02-15 13:41 UTC, Lin-cat commented on core/assets/bundles/bundle_zh_CN.properties
> +setting.automega.name = 在加入时自动控制巨象
巨像

2022-02-15 13:43 UTC, Lin-cat commented on core/assets/bundles/bundle_zh_CN.properties
> +client.command.cursor.description = 发送你的鼠标位置到聊天框
发送消息时在消息后面附加你的位置/光标位置之类的

2022-02-15 13:47 UTC, Lin-cat commented on core/assets/bundles/bundle_zh_CN.properties
> +client.command.cc.description = 轻松配置团队指挥中心
快速更改/配置你所处队伍内指挥中心的模式

2022-02-21 16:38 UTC, buthed010203 commented
~~still don't know if this is ready to merge or not~~

2022-02-21 18:27 UTC, Weathercold commented
perhape

2022-02-22 05:00 UTC, Lin-cat commented
> ~still don't know if this is ready to merge or not~

<s>just do it</s>

2022-02-27 04:34 UTC, lliioollcn commented
this is ready to merge.
if you has any problem for this, you can asked me to change it

2022-02-28 17:45 UTC, merged